### PR TITLE
Feature/CWE 347

### PR DESCRIPTION
**Pull request by timmyteo**
Adding a new Purple Belt lesson for CWE-347

### CODE REVIEW

**Comment by timmyteo** [comment]
Hi @paul-ion - do you think this one could be a good addition to the platform?

**Comment by paul-ion** [comment]
Hi @timmyteo this is great! It's a easier version than the Broken Authentication & Broken Access Control version in the Second Degree black belt. However I'm afraid I've broken this change by splitting Black Belt into two modules. Is it possible to update the PR and re-submit? Many thanks!

**Comment by timmyteo** [comment]
@paul-ion merged latest from main to resolve conflict

**Review by paul-ion — APPROVED** [review]

**Comment by paul-ion** [comment]
@timmyteo many thanks for this and sorry for the late merge. It's been a busy year...

**Pull request merged**
